### ISSUE TITLE
Status of LAME development

### ISSUE THREAD

**Issue by sergeevabc** [Chocobo1/lame_win32-build#1]
Dear @Chocobo1,
Codecs.com posted version [3.101 beta 3](https://www.free-codecs.com/download/lame_encoder.htm) built on December 2023.
Does this mean that the development of the encoder has resumed?

**Comment by Chocobo1** [comment]
>Does this mean that the development of the encoder has resumed?

Go to LAME source repo: https://sourceforge.net/p/lame/svn/HEAD/tree/ and click on History. It seems it has some activity recently.
Also https://svn.code.sf.net/p/lame/svn/trunk/lame/doc/html/history.html have a section for the next release 3.101.

Thanks for letting me know!

**Comment by sergeevabc** [comment]
Just tried your recent build of LAME v4 — it works fine on Windows 7 x64.
Thank you, @Chocobo1.

![](https://github.com/user-attachments/assets/8eb41731-71fa-4013-9f1c-d042ef132a44)
